apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-api
  namespace: dev
  labels:
    app: booking-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: booking-api
  template:
    metadata:
      labels:
        app: booking-api
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - booking-api
              topologyKey: "kubernetes.io/hostname"
      initContainers:
      - name: wait-for-deps
        image: fcavarzare/projeto-reserva:booking-api-e2d5c0553bf348b75534720d69c6e09ba2aaa1d0
        command: ['sh', '-c', 'apk add --no-cache netcat-openbsd && until nc -z -w 2 100.100.100.104 1433 && nc -z -w 2 rabbitmq-service 5672; do echo waiting for sqlserver and rabbitmq; sleep 2; done;']
        resources:
          limits:
            cpu: "50m"
            memory: "64Mi"
          requests:
            cpu: "50m"
            memory: "64Mi"
      containers:
      - name: booking-api
        image: fcavarzare/projeto-reserva:booking-api-latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: ConnectionStrings__DefaultConnection
          value: "Server=100.100.100.104;Database=BookingDb;User Id=sa;Password=Your_password123;TrustServerCertificate=True;"
        - name: ConnectionStrings__Redis
          value: "redis-service:6379"
        - name: ExternalServices__PaymentApi
          value: "http://payment-api-service:80"
        - name: ConnectionStrings__RabbitMQ
          value: "rabbitmq-service"
        resources:
          limits:
            cpu: "200m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: booking-api-service
  namespace: dev
spec:
  selector:
    app: booking-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: ClusterIP
