apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: booking-api-policy
  namespace: dev
spec:
  podSelector:
    matchLabels:
      app: booking-api
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector: {} # Permite de qualquer pod no mesmo namespace
  egress:
  - to:
    - podSelector: {} # Permite para qualquer pod no mesmo namespace
