apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: web-ui
  namespace: dev
  labels:
    release: kps
    app: web-ui
spec:
  selector:
    matchLabels:
      app: web-ui
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
