apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-ui
  namespace: qa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-ui
  template:
    metadata:
      labels:
        app: web-ui
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - web-ui
              topologyKey: "kubernetes.io/hostname"
      containers:
      - name: web-ui
        image: fcavarzare/projeto-reserva:web-ui-latest
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "200m"
            memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: web-ui-service
  namespace: qa
spec:
  selector:
    app: web-ui
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: projeto-reserva-ingress
  namespace: qa
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: projeto-reserva.dev.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: web-ui-service
            port:
              number: 80
      - path: /api/booking
        pathType: Prefix
        backend:
          service:
            name: booking-api-service
            port:
              number: 80
