apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-api
  namespace: qa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identity-api
  template:
    metadata:
      labels:
        app: identity-api
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - identity-api
              topologyKey: "kubernetes.io/hostname"
      initContainers:
      - name: wait-for-deps
        image: alpine:latest
        command: ['sh', '-c', 'until nc -z sqlserver-service 1433 && nc -z rabbitmq-service 5672; do echo waiting for sqlserver and rabbitmq; sleep 2; done;']
        resources:
          limits:
            cpu: "50m"
            memory: "64Mi"
          requests:
            cpu: "50m"
            memory: "64Mi"
        resources:
          limits:
            cpu: "50m"
            memory: "64Mi"
          requests:
            cpu: "50m"
            memory: "64Mi"
      containers:
      - name: identity-api
        image: fcavarzare/projeto-reserva:identity-api-0ce34dfac9cda9457e61dc70566fb8ac23d9b14c
        ports:
        - containerPort: 8080
        env:
        - name: ConnectionStrings__IdentityDbContext
          value: "Server=sqlserver-service;Database=IdentityDb;User Id=sa;Password=Your_password123;TrustServerCertificate=True;"
        resources:
          limits:
            cpu: "50m"
            memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: identity-api-service
  namespace: qa
spec:
  selector:
    app: identity-api
  ports:
  - port: 80
    targetPort: 8080





