apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace-governance.yaml
  - infrastructure/k8s-infra.yaml
  - infrastructure/prometheus-rules.yaml
  - booking-api/deployment.yaml
  - booking-api/hpa.yaml
  - booking-api/network-policy.yaml
  - booking-api/pdb.yaml
  - booking-api/servicemonitor.yaml
  - payment-api/deployment.yaml
  - payment-api/hpa.yaml
  - payment-api/network-policy.yaml
  - payment-api/pdb.yaml
  - payment-api/servicemonitor.yaml
  - identity-api/deployment.yaml
  - identity-api/hpa.yaml
  - identity-api/network-policy.yaml
  - identity-api/pdb.yaml
  - identity-api/servicemonitor.yaml
  - web-ui/deployment.yaml
  - web-ui/hpa.yaml
  - web-ui/network-policy.yaml
  - web-ui/pdb.yaml
  - web-ui/servicemonitor.yaml
