apiVersion: v1
kind: Namespace
metadata:
  name: qa
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources
  namespace: qa
spec:
  hard:
    requests.cpu: "4000m"
    requests.memory: "6Gi"
    limits.cpu: "8000m"
    limits.memory: "12Gi"
    pods: "20"
