apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: projeto-reserva-dev-alerts
  namespace: monitoring
  labels:
    release: kps
spec:
  groups:
  - name: projeto-reserva.dev.rules
    rules:
    - alert: BookingApiHighCpu
      expr: sum by (pod) (rate(container_cpu_usage_seconds_total{namespace="dev", container="booking-api"}[5m])) > 0.40
      for: 3m
      labels:
        severity: warning
    - alert: PaymentApiHighCpu
      expr: sum by (pod) (rate(container_cpu_usage_seconds_total{namespace="dev", container="payment-api"}[5m])) > 0.40
      for: 3m
      labels:
        severity: warning
    - alert: MicroserviceDown
      expr: kube_pod_status_ready{namespace="dev", condition="true"} == 0
      for: 2m
      labels:
        severity: critical
