apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-api
  namespace: prod
  labels:
    app: booking-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: booking-api
  template:
    metadata:
      labels:
        app: booking-api
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - booking-api
              topologyKey: "kubernetes.io/hostname"
      initContainers:
      - name: wait-for-deps
        image: alpine:latest
        command: ['sh', '-c', 'until nc -z sqlserver-service 1433 && nc -z rabbitmq-service 5672; do echo waiting for sqlserver and rabbitmq; sleep 2; done;']
        resources:
          limits:
            cpu: "50m"
            memory: "64Mi"
          requests:
            cpu: "50m"
            memory: "64Mi"
        resources:
          limits:
            cpu: "50m"
            memory: "64Mi"
          requests:
            cpu: "50m"
            memory: "64Mi"
      containers:
      - name: booking-api
        image: fcavarzare/projeto-reserva:booking-api-0ce34dfac9cda9457e61dc70566fb8ac23d9b14c
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: ConnectionStrings__DefaultConnection
          value: "Server=sqlserver-service;Database=BookingDb;User Id=sa;Password=Your_password123;TrustServerCertificate=True;"
        - name: ConnectionStrings__Redis
          value: "redis-service:6379"
        - name: ExternalServices__PaymentApi
          value: "http://payment-api-service:80"
        - name: ConnectionStrings__RabbitMQ
          value: "rabbitmq-service"
        resources:
          limits:
            cpu: "50m"
            memory: "128Mi"
          requests:
            cpu: "50m"
            memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: booking-api-service
  namespace: prod
spec:
  selector:
    app: booking-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: ClusterIP





