apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: booking-api
  namespace: prod
  labels:
    release: kps
    app: booking-api
spec:
  selector:
    matchLabels:
      app: booking-api
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
