name: ci-booking-api

on:
  push:
    branches: ["main"]
    paths:
      - "src/Services/Booking/**"

permissions:
  contents: write

env:
  IMAGE_NAME: fcavarzare/projeto-reserva

jobs:
  build_push_and_update:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image locally
        uses: docker/build-push-action@v6
        with:
          context: .
          file: src/Services/Booking/Booking.API/Dockerfile
          push: false
          load: true
          tags: ${{ env.IMAGE_NAME }}:temp-scan

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.IMAGE_NAME }}:temp-scan
          format: 'table'
          exit-code: 0
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL'

      - name: Build & Push final image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: src/Services/Booking/Booking.API/Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:booking-api-${{ github.sha }}
            ${{ env.IMAGE_NAME }}:booking-api-latest

      - name: Pause Auto Update
        run: echo "Automatic manifest update is temporarily paused to stabilize cluster"
