name: ci-booking-api

on:
  push:
    branches: ["main"]
    paths:
      - "src/Services/Booking/**"

permissions:
  contents: write

env:
  IMAGE_NAME: fcavarzare/projeto-reserva

jobs:
  build_push_and_update:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image locally
        uses: docker/build-push-action@v6
        with:
          context: .
          file: src/Services/Booking/Booking.API/Dockerfile
          push: false
          load: true
          tags: ${{ env.IMAGE_NAME }}:temp-scan

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.IMAGE_NAME }}:temp-scan
          format: 'table'
          exit-code: 0
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL'

      - name: Build & Push final image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: src/Services/Booking/Booking.API/Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:booking-api-${{ github.sha }}
            ${{ env.IMAGE_NAME }}:booking-api-latest

      - name: Update Manifests and Push
        # - name: Update Kubernetes manifests
        #   run: |
        #     git config --global user.name "github-actions[bot]"
        #     git config --global user.email "github-actions[bot]@users.noreply.github.com"
        #     
        #     # 1. Update DEV
        #     DEV_FILE="deploy/dev/booking-api/deployment.yaml"
        #     NEW_IMAGE="${IMAGE_NAME}:booking-api-${GITHUB_SHA}"
        #     awk -v new_image="$NEW_IMAGE" 'BEGIN{done=0} {if(!done && $1=="image:"){match($0, /^[[:space:]]*/); indent=substr($0, RSTART, RLENGTH); print indent "image: " new_image; done=1} else print}' "$DEV_FILE" > "$DEV_FILE.tmp" && mv "$DEV_FILE.tmp" "$DEV_FILE"
        #     git add "$DEV_FILE"
        #     
        #     git commit -m "chore: update booking-api image to ${GITHUB_SHA} [skip ci]" || exit 0
        #     
        #     for i in {1..5}; do
        #       git pull --rebase origin main
        #       git push origin HEAD:main && break || sleep 5
        #     done
